Add support for ips
Ostorlab/agent_whatweb pull request #16
Opened 2022-08-25 12:34 UTC by RabsonJ

2022-08-25 16:16 UTC, amine3 requested changes

2022-08-25 16:16 UTC, amine3 commented on agent/whatweb_agent.py
> +            is_target_already_processed = self._is_target_already_processed(
no need to use the variable is_target_already_processed, you can do the if check directly on the function result

2022-08-25 16:16 UTC, amine3 commented on agent/whatweb_agent.py
> +            if message.data.get('port') is not None:
can you add a comment on this part

2022-08-25 16:16 UTC, amine3 commented on agent/whatweb_agent.py
> +                for address in addresses.hosts():
no need for the for loop here since it is a single address, you can just do return str(ipaddress.ip_network(host))

2022-08-28 08:41 UTC, 3asm requested changes

2022-08-28 08:41 UTC, 3asm commented on agent/whatweb_agent.py
> +                result = self.add_ip_network('agent_whois_ip_asset', addresses, lambda net: f'X_{net}_Y')
The lambda must include schema and port.
lambda net : f'{protocol}_{net}_{protocol}'

2022-08-29 09:07 UTC, 3asm approved these changes

2022-08-29 09:08 UTC, merged