Send exact target where the fingerprint was found.
Ostorlab/agent_whatweb pull request #22
Opened 2022-10-18 10:13 UTC by deadly-panda

With a sprinkle of refactoring!

2022-10-18 22:01 UTC, 3asm requested changes

2022-10-19 07:57 UTC, deadly-panda commented on agent/whatweb_agent.py
> +            return agent_report_vulnerability_mixin.AssetLocation(asset=asset, metadata=metadata)
That's exactly why this PR is a draft 😄

2022-10-20 10:36 UTC, 3asm requested changes

2022-10-20 10:36 UTC, 3asm commented on agent/whatweb_agent.py
> +from typing import List, Optional, Dict, Any, Union
Use | instead of union.

2022-10-20 10:36 UTC, 3asm commented on agent/whatweb_agent.py
> +    def _prepare_targets(self, message: msg.Message) -> List[Union[DomainTarget, IPTarget]]:
| instead of union as we support 3.10.

2022-10-20 10:36 UTC, 3asm commented on agent/whatweb_agent.py
> +    def _get_msg_data(self, target: DomainTarget | IPTarget,
See, that's inconsistent in a single file!

2022-10-20 10:36 UTC, 3asm commented on tests/whatweb_test.py
> +            assert any(fingerprint.data.get('vulnerability_location') == fp_location for fingerprint in agent_mock)
Missing unit test for domain name.

2022-10-21 01:51 UTC, 3asm requested changes

2022-10-21 01:51 UTC, 3asm commented on agent/whatweb_agent.py
> +            return vuln_mixin.VulnerabilityLocation(asset=asset, metadata=metadata)
Shouldn't this be URL as metadata for domain.

2022-10-24 11:13 UTC, merged