fix line overwriting on pfsense and mobsf plugins
Ostorlab/agent_whatweb pull request #55
Opened 2024-09-02 15:12 UTC by ybadaoui-ostorlab

2024-09-02 15:15 UTC, PiranhaSa submitted a review, later dismissed

2024-09-02 15:19 UTC, nmasdoufi-ol submitted a review, later dismissed

2024-09-02 16:11 UTC, benyissa submitted a review, later dismissed

2024-09-02 16:21 UTC, adnaneserrar approved these changes

2024-09-02 17:43 UTC, ohachimOs approved these changes

2024-09-03 09:49 UTC, 3asm requested changes

2024-09-03 09:49 UTC, 3asm commented on plugins/pfsense.rb
> +			:text => "<h4>Login to pfSense</h4>"
Please fix formatting and add a description of the PR.

2024-09-03 16:36 UTC, ohachimOs approved these changes

2024-09-03 16:45 UTC, 3asm approved these changes

2024-09-03 16:45 UTC, merged